name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup dart
        uses: dart-lang/setup-dart@v1

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Configure Git
        run: |
          git config user.name "Tpay Auto Commit"
          git config user.email devs@tpay.com

      - name: Create release branch
        run: git checkout -b release/${{ github.event.inputs.version }}

      - name: Generate documentation
        run: dart doc --output ./doc .

      - name: Commit docs
        run: |
          git add doc/ 
          git commit --allow-empty -m "Update docs"
          
      - name: Push release branch
        run: git push origin release/${{ github.event.inputs.version }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: ${{ github.event.inputs.version }} into master