name: Publish to pub.dev

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup dart
        uses: dart-lang/setup-dart@v1

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Configure Git
        run: |
          git config user.name "Tpay Auto Commit"
          git config user.email devs@tpay.com

      - name: Publish dry run
        run: flutter pub publish --dry-run

      - name: Publish
        run: flutter pub publish --force

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.PAT }}
          body: "Release is available on pub.dev repository. Run 'flutter pub get flutter_tpay'"